title: Hello! I'm Rudder
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: Rudder # add your name
author-img: rudder-wu.png # add your photo
about-author: Enjoy Life! # add description
website: worldkingwu.com #add your website
email: worldkingwu@gmail.com # add your Email address
github: worldkingwu # add your Github handle
weibo: 5544217447/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1 #add your weibo address
twitter: # add your Twitter handle
facebook: # add your Facebook handle
linkedin: # add your Linkedin handle

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

#IntenseDebate
intensedebate_comments: false


# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
